### ISSUE TITLE
Tutorial not working

### ISSUE THREAD

**Issue by baum1234** [RaphC/selenese4j-maven-plugin#36]
Hello,

I followed the tutorial.

First, there is no path to `/src/main/resources/selenium/html/scenarii` so I cre-ated that folder.
After that I put there all files that are in the tutorial and run the test.

After that there was no testSourceGenerationDirectoryPath folder or the MySeleniumTestCase.java file anywhere in the project.

Also I searched for some properties and they are all hardcoded into the code ... I guess it can't work like the tutorial.

**Comment by RaphC** [comment]
Hi,

Do you have any log ? Can you send me your plugin configuration ?

Regards

**Comment by baum1234** [comment]
No or I didn't find them.

**Comment by RaphC** [comment]
So 

You added the plugin in your pom.xml
You Created the folder /src/main/resources/selenium/html/scenarii then added some files
And then launched the plugin.

Eventually no java files generated ?

**Comment by baum1234** [comment]
I used the same pom.xml that is in this git. And yes no java files are generated.

**Comment by RaphC** [comment]
Hi,

You have to define the goal you want to run and the phase like this.

```
            <groupId>com.github.raphc</groupId>
            <artifactId>selenese4j-maven-plugin</artifactId>
            <version>2.2</version>
            <executions>
                <execution>
                    <goals><goal>transform</goal></goals>
                    <phase>generate-sources</phase>
                </execution>
            </executions>
```

You have to create the directories src/main/resources/selenium/config and src/main/resources/selenium/html/scenarii then add en empty selenese4j.propeties in src/main/resources/selenium/config

You can also update the plugin version

I updated the tutorial. Let me know If you have any trouble.

Regards

**Comment by xsalefter** [comment]
Hi @RaphC,

I've been tried the tutorial, but as @baum1234 mentioned, the Tutorial not working. To be precise, generated java files from the tutorial produce uncompiled Java file. I tried reproduce your tutorial, and this is the source code: https://github.com/xsalefter/selenese4jexample

Thanks

**Comment by RaphC** [comment]
Hi

The goal of this plugin is first to translate the selenium scenariis to Junit Java source files. 

As it is explained in the page [Writing-Automate-Selenium-RC-Testing-Integrations](https://github.com/RaphC/selenese4j-maven-plugin/wiki/Writing-Automate-Selenium-RC-Testing-Integrations) to compile the generated sources you have to :  

Add the following dependencies 

``` xml
<dependencies>
    <dependency>
        <groupId>org.seleniumhq.selenium.client-drivers</groupId>
        <artifactId>selenium-java-client-driver</artifactId>
        <version>1.0.2</version>
    </dependency>
    <dependency>
        <groupId>log4j</groupId>
        <artifactId>log4j</artifactId>
    </dependency>
    <dependency>
        <groupId>junit</groupId>
        <artifactId>junit</artifactId>
    </dependency>
    <dependency>
        <groupId>commons-io</groupId>
        <artifactId>commons-io</artifactId>
        <version>1.4</version>
    </dependency>
</dependencies>
```

Added the directory where the source are generated as a test source directory thanks to build-helper-maven-plugin

``` xml
<plugin>
<groupId>org.codehaus.mojo</groupId>
<artifactId>build-helper-maven-plugin</artifactId>
<version>1.7</version>
<executions>
        <execution>
            <phase>generate-test-sources</phase>
            <goals><goal>add-test-source</goal></goals>
            <configuration>
                <sources>
                    <source>${basedir}/target/generated-it-java</source>
                </sources>
            </configuration>
        </execution>
    </executions>
</plugin>
```

Finally, at hte end of the compile phase, your JUnit test files should be compiled.

Regards,

**Comment by xsalefter** [comment]
Hi @RaphC,

Thanks for your reply. I did what you said. This is one of compile error that I found. This is generated based on your tutorial without any modification:

![selenese4jerror](https://cloud.githubusercontent.com/assets/510438/14409629/09b2ba50-ff43-11e5-8d6a-25094561da5f.png)

I think the error because multi-line statement when generating javascript code, which is something like this:

``` java
String popupID =selenium.getEval("{var
                    windowId; for(var x in selenium.browserbot.openedWindows )
                    {windowId=x;} }"); selenium.waitForPopUp(popupID,
                    "90000");selenium.selectWindow(popupID);selenium.windowFocus();
```

I tried to clone the project, but not sure where exactly the source code that generating this one.

Thanks.

**Comment by RaphC** [comment]
Hi,

You're right. It seems this is an issue. Did you try to put the following line on a single line 

<td>{@snippet:java String popupID =selenium.getEval("{var windowId; for(var x in selenium.browserbot.openedWindows ) {windowId=x;} }");
    selenium.waitForPopUp(popupID, "90000");selenium.selectWindow(popupID);selenium.windowFocus(); @snippet}

**Comment by xsalefter** [comment]
Hi @RaphC,

If I edit generated code to single line, of course it is work. Seems like generator translate multiline `<td />` tag as is, thus generate this compile error.

FYI: html2wd goal is also broken. It produce more horrible compile error than transform goal.

Thanks.

**Comment by RaphC** [comment]
I would say in the scenario html file.

:) html2wd is an experimental goal...  not the best way to generate.

The bug on multiline was already mentionned in the issue #24 

You can create an issue for the html2wd bugs.

Regards,
