### ISSUE TITLE
License

### ISSUE THREAD

**Issue by xsalefter** [RaphC/selenese4j-maven-plugin#38]
Hi there.. What license for this project? I can't see any license file related to this project. Thanks.

**Comment by RaphC** [comment]
Hi

The licence is decribed in the pom.xml file

``` xml
<licenses>
        <license>
            <name>The MIT License</name>
            <url>http://opensource.org/licenses/mit-license</url>
            <distribution>repo</distribution>
        </license>
    </licenses>
```

Regards,

**Comment by xsalefter** [comment]
Ah, Ok. Thanks for pointing to pom.xml. I'll close this now.
